name: Metrics

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - .github/workflows/metrics.yml

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: jairure16-lab
          template: classic
          base: header, activity, community, repositories, metadata
          plugins_errors_fatal: false
          config_timezone: America/Panama
          plugin_languages: yes
          plugin_languages_categories: markup, programming
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
